### ISSUE TITLE
How to load datasets like `torchvision.datasets.ImageFolder`?

### ISSUE THREAD

**Issue by RahulBhalley** [ml-explore/mlx-data#14]
How to load datasets like [`torchvision.datasets.ImageFolder`](https://pytorch.org/vision/stable/generated/torchvision.datasets.ImageFolder.html#torchvision.datasets.ImageFolder)? Following is the directory & files format. This kind of loading is very much needed. 
```
root/dog/xxx.png
root/dog/xxy.png
root/dog/[...]/xxz.png

root/cat/123.png
root/cat/nsdf3.png
root/cat/[...]/asd932_.png
```
I want to train a GAN and potentially submit a PR in [ml-explore/mlx-examples](https://github.com/ml-explore/mlx-examples) repo.

**Comment by angeloskath** [comment]
Better late than never so feel free to use `load_images_from_folder` which was added in #29 . It will be added to the docs shortly.

**Comment by RahulBhalley** [comment]
Cool.
