### ISSUE TITLE
`key_transform` and `buffer_from_vector` should support mlx.core arrays instead of throwing `Array is not writeable`

### ISSUE THREAD

**Issue by dastrobu** [ml-explore/mlx-data#20]
Consider the following minimal example:

```
b = dx.buffer_from_vector(list(dict(i=i) for i in range(5)));
print(b.key_transform("i", lambda x: mx.ones(3), output_key="o"))
```

This raises `ValueError: array is not writeable`. It works with numpy arrays, though: `lambda x: np.ones(3)`. 

I am assuming that `mx.array` is missing some protocol to support this, so I am not sure if I should report this here or in ml-explore/mlx. 

The current situation is a bit strange to be forced to init a numpy array only to be converted to mlx later on.

The same problem arise when creating an `mx.array` for `buffer_from_vector`: `b = dx.buffer_from_vector(list(dict(i=mx.array(i)) for i in range(5)));`.

**Comment by angeloskath** [comment]
Closing since it is now supported after merging ml-explore/mlx#323 .
