### ISSUE TITLE
PNG Image support 

### ISSUE THREAD

**Issue by dc-dc-dc** [ml-explore/mlx-data#38]
Wish I bumped into this repo earlier, created a similar lib and see that you guys have support for most of what I was working on. 

I did notice that png support is missing afaict, is there an interest in adding it? I was utilizing `libpng` and can bring it over if desired.

**Comment by angeloskath** [comment]
Definitely an interest in adding png support. `stb_image` should already support png files so if we don't we may have misconfigured something.

**Comment by dc-dc-dc** [comment]
Cool, after taking a quick look through stb_image docs it looks like they do support png so no need for a libpng wrapper. Closing
