### ISSUE TITLE
Enable Discussions for this repo

### ISSUE THREAD

**Issue by RahulBhalley** [ml-explore/mlx-data#44]
Hello,

I would request the team to please enable Discussions for this repository as datasets are of utmost importance in deep learning algorithms and I (probably others too) have a lot of questions that don't mean to be related to issues with the source code but regarding the usage of it. 

Thanks.

**Comment by awni** [comment]
I think they are enabled..? I just made a test discussion #46 , you can check and see. If it doesn't work for you let me know and I will reopen this.

**Comment by RahulBhalley** [comment]
Thanks! Now the Discussion tab is visible.
