### ISSUE TITLE
How to decide prefetch batch and threads?

### ISSUE THREAD

**Issue by RahulBhalley** [ml-explore/mlx-data#45]
Here's a code snippet from [Buffers, Streams and Samples](https://ml-explore.github.io/mlx-data/build/html/buffers_streams_samples.html#streams) webpage.

```python3
# We can define the rest of the processing pipeline using streams.
# 1. First shuffle the buffer
# 2. Make a stream
# 3. Batch and then prefetch
dset = (
    dset
    .shuffle()
    .to_stream()  # <-- making a stream from the shuffled buffer
    .batch(32)
    .prefetch(8, 4)  # <-- prefetch 8 batches using 4 threads
)

# Now we can iterate over dset
sample = next(dset)
```

I don't know how to decide the values for prefetch. Could someone suggest a general rule?

**Comment by angeloskath** [comment]
There is no general rule but the thinking is the following: The prefetch defines how many samples we will attempt to prefetch. The threads defines how many threads will be doing the prefetching in parallel.

If you have a really fast pipeline then keeping these numbers low is not a problem. Even 1 and 1 would work fine for a really fast pipeline or a really slow processing loop. While the current sample/batch is being processes the next is prepared in 1 background thread.

Now otoh if you need to process thousands of images per second for instance you need by definition many threads. Also the prefetch size has to do be large enough that the threads always have something to do and are not simply waiting for samples to be consumed.

**Comment by angeloskath** [comment]
As a more general comment I would say that threads about half or 3/4 the virtual cores of the machine and prefetch about 2x-3x the number of threads is a pretty decent default.

**Comment by RahulBhalley** [comment]
Okay, thank you for this information.

**Comment by RahulBhalley** [comment]
I have M1 Air (8 cores) so I should use 4-6 threads and 8-12 or 12-18 batches, right? 

Does the size of sample array also matters in deciding the threads and batches to prefetch? For instance, for size (128, 128, 3) the prefetch could have higher values while for size (1024, 1024, 3) prefetch should have lower values?

**Comment by angeloskath** [comment]
It depends on the speed of the computation as well. `(1024, 1024, 3)` is 12MB of float32 so keeping a 10 batches of 10 in memory is a significant portion of the 8GB RAM (~1GB). However, it also unlikely that you will be able to process 100s of megapixel images per second on an M1 Air so no need for a big prefetch buffer.

Another pattern to try when your batch is large in memory so you can keep many in a prefetch buffer is to do two prefetches, one before and one after the batching as follows:

```python
dset = (
    dset
    .shuffle()
    .to_stream()
    .prefetch(32, 8)  # <-- prefetch before batching so this handles
                      #     reading, decoding and preparing individual images

    .batch(16)  # <-- batch should be less than the prefetch above

    .prefetch(2, 1) # <-- final prefetch just so that a batch is prepared
                    #     and waiting for you no need for many threads or large
                    #     prefetch buffers
)
```

**Comment by RahulBhalley** [comment]
Thanks. Using prefetch twice is interesting.
